[tool.poetry]
name = "lda"
version = "2.1.0"
description = "Topic modeling with latent Dirichlet allocation"
authors = ["lda developers <lda-users@googlegroups.com>"]
license = "MPL 2.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.25.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
cython = "^0.29.36"
black = "^23.7.0"
isort = "^5.12.0"
pre-commit = "^3.3.3"

[tool.poetry.build]
generate-setup-file = true
script = "build.py"

[tool.isort]
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3

[build-system]
requires = ["poetry-core", "setuptools", "cython"]
build-backend = "poetry.core.masonry.api"
