name: CI & CD

on:
  push:
    tags:
      - '*.*.*'

env:
  PYTHONDONTWRITEBYTECODE: 1

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install "poetry~=1.2"

      - name: Install Python dependencies
        run: poetry install --only build --no-root

      - name: Build wheels
        run: poetry run cibuildwheel --output-dir dist

      - name: Build source distribution
        run: poetry build --format sdist

      - name: Deploy wheels
        run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PW }} --skip-existing
