name: CI & CD

on:
  push:
    # tags: ["*"]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install Python dependencies
        run: poetry install --only build --no-root

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      - name: Build source distribution (only once on Linux)
        if: matrix.os == 'ubuntu-latest'
        run: poetry build --format sdist

      - name: Deploy wheels
        run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PW }} --dry-run
